# Generated by Django 5.1.5 on 2025-07-21 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('in_stock', 'In_stock'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('rented', 'Rented')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified_pre_owned', 'Certified_pre_owned')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to='car_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=30)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('vehicle_identification_number', models.CharField(max_length=17, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.IntegerField()),
                ('engine_type', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT')], max_length=20)),
                ('number_of_doors', models.PositiveSmallIntegerField()),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_images')),
                ('accident_history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.caravailability')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carcondition')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.carmake')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
